/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import static databases.CrudModel.insert_OrderCustomer;
import javax.swing.JOptionPane;
import static pointofsale_backend.Frame_control.*;

/**
 *
 * @author Rifky <qnoy.rifky@gmail.com>
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form CobaLayout
     */
    public HalamanUtama() {
//        giveAccess = true;//for testing set to true ,live pls comment with //
        if (get_accessApp()) {
            initComponents();
            hu_lbl_userjabatan.setText(get_jabatanPegawai());
            hu_lbl_nip.setText(get_nipPegawai());
            if (get_levelaccessApp().equals("superadmin")) {
                jMenuItem_mnj_userapp.setVisible(true);
                hu_btn_mjnmeja.setVisible(true);
                hu_lbl_pchostname.setText(readConf.get_config("pc_hostname"));
                hu_lbl_pcipaddress.setText(readConf.get_config("pc_ipaddress"));
            }else{
                jMenuItem_mnj_userapp.setVisible(false);
                hu_btn_mjnmeja.setVisible(false);
            }
            
            
        } else {
            int result = JOptionPane.showConfirmDialog(this, "anda belum login !", this.getTitle(), JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                tampilLogin_UserApp();
            } else if (result == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }

    public static void mulaiOrder(int var_id_meja) {
        String val_kodemeja = getKodeMeja(var_id_meja);
        String val_kodeorder = null;
        String val_kodeorderDetail = null;
        String _existsKodeOrder;
        String _existsKodeOrderdetail;
        String _existsRp_tagihan;
        String set_text_tombol;
        boolean set_tombol_bayar;

        getStatusMejaorder(val_kodemeja);
        if (notif_cek_order_tdklunas) {
            //ditemukan kode meja dan tidak lunas
            _existsKodeOrder = get_existsRow_order(val_kodemeja, "kode_order");
            _existsKodeOrderdetail = get_existsRow_order(val_kodemeja, "kode_orderdetail");
            _existsRp_tagihan = get_existsRow_order(val_kodemeja, "rp_total");
            System.out.println("kode order" + _existsKodeOrder);
            System.out.println("kode detail order " + _existsKodeOrderdetail);
            System.out.println("kdmeja @hal utama = " + val_kodemeja);
            set_text_tombol = "Lihat order";
            set_tombol_bayar = true;
            tampil_Popup_pilMeja(val_kodemeja, _existsKodeOrder, _existsKodeOrderdetail, _existsRp_tagihan, set_text_tombol, set_tombol_bayar);
        } else {
            insert_OrderCustomer(var_id_meja);
            _existsKodeOrder = get_existsRow_order(val_kodemeja, "kode_order");
            _existsKodeOrderdetail = get_existsRow_order(val_kodemeja, "kode_orderdetail");
            _existsRp_tagihan = get_existsRow_order(val_kodemeja, "rp_total");
            set_text_tombol = "Mulai order";
            set_tombol_bayar = false;
            tampil_Popup_pilMeja(val_kodemeja, _existsKodeOrder, _existsKodeOrderdetail, _existsRp_tagihan, set_text_tombol, set_tombol_bayar);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        layout_meja_dan_menu = new javax.swing.JSplitPane();
        jpanel_meja = new javax.swing.JPanel();
        btn_meja1 = new javax.swing.JButton();
        btn_meja2 = new javax.swing.JButton();
        btn_meja3 = new javax.swing.JButton();
        btn_meja4 = new javax.swing.JButton();
        btn_meja5 = new javax.swing.JButton();
        btn_meja6 = new javax.swing.JButton();
        btn_meja7 = new javax.swing.JButton();
        btn_meja8 = new javax.swing.JButton();
        btn_meja9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpanel_menu_kanan = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        hu_btn_mjnmeja = new javax.swing.JButton();
        layout_footer = new javax.swing.JSplitPane();
        jPanel_footer_kiri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hu_lbl_nip = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hu_lbl_userjabatan = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hu_lbl_pchostname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hu_lbl_pcipaddress = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_mnj_userapp = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point Of Sale");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1028, 1024));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName("frame_hal_utama"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        layout_meja_dan_menu.setMinimumSize(new java.awt.Dimension(1024, 436));
        layout_meja_dan_menu.setPreferredSize(new java.awt.Dimension(1024, 436));

        jpanel_meja.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_meja.setMinimumSize(new java.awt.Dimension(800, 400));
        jpanel_meja.setPreferredSize(new java.awt.Dimension(800, 400));
        jpanel_meja.setLayout(new java.awt.GridLayout(3, 3));

        btn_meja1.setBackground(new java.awt.Color(103, 161, 229));
        btn_meja1.setForeground(new java.awt.Color(255, 255, 255));
        btn_meja1.setText("MEJA1");
        btn_meja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meja1ActionPerformed(evt);
            }
        });
        jpanel_meja.add(btn_meja1);

        btn_meja2.setBackground(btn_meja1.getBackground());
        btn_meja2.setForeground(btn_meja1.getForeground());
        btn_meja2.setText("MEJA2");
        btn_meja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meja2ActionPerformed(evt);
            }
        });
        jpanel_meja.add(btn_meja2);

        btn_meja3.setBackground(btn_meja1.getBackground());
        btn_meja3.setForeground(btn_meja1.getForeground());
        btn_meja3.setText("MEJA3");
        jpanel_meja.add(btn_meja3);

        btn_meja4.setBackground(btn_meja1.getBackground());
        btn_meja4.setForeground(btn_meja1.getForeground());
        btn_meja4.setText("MEJA4");
        jpanel_meja.add(btn_meja4);

        btn_meja5.setBackground(btn_meja1.getBackground());
        btn_meja5.setForeground(btn_meja1.getForeground());
        btn_meja5.setText("MEJA5");
        jpanel_meja.add(btn_meja5);

        btn_meja6.setBackground(btn_meja1.getBackground());
        btn_meja6.setForeground(btn_meja1.getForeground());
        btn_meja6.setText("MEJA6");
        jpanel_meja.add(btn_meja6);

        btn_meja7.setBackground(btn_meja1.getBackground());
        btn_meja7.setForeground(btn_meja1.getForeground());
        btn_meja7.setText("MEJA7");
        btn_meja7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meja7ActionPerformed(evt);
            }
        });
        jpanel_meja.add(btn_meja7);

        btn_meja8.setBackground(btn_meja1.getBackground());
        btn_meja8.setForeground(btn_meja1.getForeground());
        btn_meja8.setText("MEJA8");
        jpanel_meja.add(btn_meja8);

        btn_meja9.setBackground(btn_meja1.getBackground());
        btn_meja9.setForeground(btn_meja1.getForeground());
        btn_meja9.setText("MEJA9");
        btn_meja9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_meja9ActionPerformed(evt);
            }
        });
        jpanel_meja.add(btn_meja9);

        layout_meja_dan_menu.setLeftComponent(jpanel_meja);

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 472));

        jpanel_menu_kanan.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_menu_kanan.setMinimumSize(new java.awt.Dimension(200, 436));
        jpanel_menu_kanan.setPreferredSize(new java.awt.Dimension(200, 436));

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Laporan penjualan");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Manajemen pesanan menu");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        hu_btn_mjnmeja.setBackground(new java.awt.Color(51, 51, 51));
        hu_btn_mjnmeja.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        hu_btn_mjnmeja.setForeground(new java.awt.Color(255, 255, 255));
        hu_btn_mjnmeja.setText("Manajemen Meja");
        hu_btn_mjnmeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hu_btn_mjnmejaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_menu_kananLayout = new javax.swing.GroupLayout(jpanel_menu_kanan);
        jpanel_menu_kanan.setLayout(jpanel_menu_kananLayout);
        jpanel_menu_kananLayout.setHorizontalGroup(
            jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_menu_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hu_btn_mjnmeja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanel_menu_kananLayout.setVerticalGroup(
            jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_menu_kananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hu_btn_mjnmeja, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel_menu_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel_menu_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        layout_meja_dan_menu.setRightComponent(jPanel2);

        layout_footer.setMinimumSize(new java.awt.Dimension(1024, 150));
        layout_footer.setPreferredSize(new java.awt.Dimension(1024, 150));

        jPanel_footer_kiri.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_footer_kiri.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar pesanan"));
        jPanel_footer_kiri.setMinimumSize(new java.awt.Dimension(700, 100));
        jPanel_footer_kiri.setPreferredSize(new java.awt.Dimension(700, 174));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MJ001", "ORD0001", "azmi", "kasir1"}
            },
            new String [] {
                "Kode meja", "Kode order", "Pelayan", "Kasir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel_footer_kiriLayout = new javax.swing.GroupLayout(jPanel_footer_kiri);
        jPanel_footer_kiri.setLayout(jPanel_footer_kiriLayout);
        jPanel_footer_kiriLayout.setHorizontalGroup(
            jPanel_footer_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel_footer_kiriLayout.setVerticalGroup(
            jPanel_footer_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        layout_footer.setLeftComponent(jPanel_footer_kiri);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        jLabel2.setText(":");

        hu_lbl_nip.setText("user Nip");

        jLabel4.setText("Nip");

        jLabel5.setText("Jabatan");

        jLabel6.setText(":");

        hu_lbl_userjabatan.setText("user level");

        jLabel8.setText("Pchostname");

        jLabel9.setText(":");

        hu_lbl_pchostname.setText("hostname");

        jLabel11.setText("ip address");

        jLabel12.setText(":");

        hu_lbl_pcipaddress.setText("0.0.0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hu_lbl_nip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hu_lbl_userjabatan, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hu_lbl_pchostname, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hu_lbl_pcipaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hu_lbl_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hu_lbl_userjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hu_lbl_pchostname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hu_lbl_pcipaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 72, Short.MAX_VALUE))
        );

        layout_footer.setRightComponent(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("point of sale software 2019");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layout_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layout_meja_dan_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(layout_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layout_meja_dan_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(285, Short.MAX_VALUE)))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(150, 30));

        jMenu2.setText("Menu aplikasi");

        jMenuItem_mnj_userapp.setText("Manajemen user aplikasi");
        jMenuItem_mnj_userapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_mnj_userappActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_mnj_userapp);

        jMenuItem1.setText("Tentang aplikasi");
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("halaman_utama");

        setSize(new java.awt.Dimension(1040, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_mnj_userappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_mnj_userappActionPerformed
        // TODO add your handling code here:
        tampilCrud_UserApp();
    }//GEN-LAST:event_jMenuItem_mnj_userappActionPerformed

    private void hu_btn_mjnmejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hu_btn_mjnmejaActionPerformed
        // TODO add your handling code here:
        tampil_NotAvailable();
    }//GEN-LAST:event_hu_btn_mjnmejaActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        tampil_formCrudMenu();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        tampilForm_LapPenjualan();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_meja9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meja9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_meja9ActionPerformed

    private void btn_meja7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meja7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_meja7ActionPerformed

    private void btn_meja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meja2ActionPerformed
        // TODO add your handling code here:
        mulaiOrder(2);
    }//GEN-LAST:event_btn_meja2ActionPerformed

    private void btn_meja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_meja1ActionPerformed
        mulaiOrder(1);
    }//GEN-LAST:event_btn_meja1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Logout ?", this.getTitle(), JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
            setClean_sesi();//clean atribut value
            tampilLogin_UserApp();
        } else if (result == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (looksAndFeel.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
                //set biar di tengah         

                //munculin framenya
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_meja1;
    private javax.swing.JButton btn_meja2;
    private javax.swing.JButton btn_meja3;
    private javax.swing.JButton btn_meja4;
    private javax.swing.JButton btn_meja5;
    private javax.swing.JButton btn_meja6;
    private javax.swing.JButton btn_meja7;
    private javax.swing.JButton btn_meja8;
    private javax.swing.JButton btn_meja9;
    private javax.swing.JButton hu_btn_mjnmeja;
    public static javax.swing.JLabel hu_lbl_nip;
    public static javax.swing.JLabel hu_lbl_pchostname;
    public static javax.swing.JLabel hu_lbl_pcipaddress;
    public static javax.swing.JLabel hu_lbl_userjabatan;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_mnj_userapp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_footer_kiri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel_meja;
    private javax.swing.JPanel jpanel_menu_kanan;
    private javax.swing.JSplitPane layout_footer;
    private javax.swing.JSplitPane layout_meja_dan_menu;
    // End of variables declaration//GEN-END:variables
}
