/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import static databases.CrudModel.insert_OrderCustomer;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import static pointofsale_backend.Frame_control.*;
import pointofsale_backend.ButtonGenerator;

/**
 *
 * @author Rifky <qnoy.rifky@gmail.com>
 */
public class HalamanUtama1 extends javax.swing.JFrame {
//    jpanel_meja
    public static int start_buttons = 1;
    public static int maximal_buttons = 20;
    public static int total_buttons = 9;
    
    /**
     * Creates new form CobaLayout
     * @param e
     */

    private void jButton_gen_ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if (evt.getActionCommand().contains("meja")) {
            System.out.println("" + evt.getActionCommand());
        }
    } 
    public void button_generator() {
        JButton[] buttons = new JButton[maximal_buttons];
        for (start_buttons =1 ; start_buttons <= total_buttons; start_buttons++) {
                String str_start_buttons = String.valueOf(start_buttons);
                buttons[start_buttons] = new JButton("meja"+start_buttons);
                buttons[start_buttons].setActionCommand("meja"+start_buttons);
                buttons[start_buttons].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton_gen_ActionPerformed(evt);
                    }
                });

                jpanel_meja2.add(buttons[start_buttons]);
        }
    }

    public HalamanUtama1() {
//        Container container = getContentPane();
//        //set_JPnel(JPanel panela,JPanel panelb,JPanel panelc,Container container){
//        int baris = 3;
//        int kolom = 3;
//jpanel_meja2.setLayout(new java.awt.BorderLayout());
        

        giveAccess = true;//for testing set to true ,live pls comment with //
        if (giveAccess) {
            initComponents();
        } else {
            int result = JOptionPane.showConfirmDialog(this, "anda belum login !", this.getTitle(), JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.YES_OPTION) {
                tampilLogin_UserApp();
            } else if (result == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }

    public static void mulaiOrder(int var_id_meja) {
        String val_kodemeja = getKodeMeja(var_id_meja);
        String val_kodeorder = null;
        String val_kodeorderDetail = null;
        String _existsKodeOrder;
        String _existsKodeOrderdetail;
        String _existsRp_tagihan;
        String set_text_tombol;
        boolean set_tombol_bayar;

        getStatusMejaorder(val_kodemeja);
        if (notif_cek_order_tdklunas) {
            //ditemukan kode meja dan tidak lunas
            _existsKodeOrder = get_existsRow_order(val_kodemeja, "kode_order");
            _existsKodeOrderdetail = get_existsRow_order(val_kodemeja, "kode_orderdetail");
            _existsRp_tagihan = get_existsRow_order(val_kodemeja, "rp_total");
            System.out.println("kode order" + _existsKodeOrder);
            System.out.println("kode detail order " + _existsKodeOrderdetail);
            System.out.println("kdmeja @hal utama = " + val_kodemeja);
            set_text_tombol = "Edit order";
            set_tombol_bayar = true;
            tampil_Popup_pilMeja(val_kodemeja, _existsKodeOrder, _existsKodeOrderdetail, _existsRp_tagihan, set_text_tombol, set_tombol_bayar);
        } else {
            insert_OrderCustomer(var_id_meja);
            _existsKodeOrder = get_existsRow_order(val_kodemeja, "kode_order");
            _existsKodeOrderdetail = get_existsRow_order(val_kodemeja, "kode_orderdetail");
            _existsRp_tagihan = get_existsRow_order(val_kodemeja, "rp_total");
            set_text_tombol = "Mulai order";
            set_tombol_bayar = false;
            tampil_Popup_pilMeja(val_kodemeja, _existsKodeOrder, _existsKodeOrderdetail, _existsRp_tagihan, set_text_tombol, set_tombol_bayar);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        layout_meja_dan_menu = new javax.swing.JSplitPane();
        jpanel_meja2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jpanel_menu_kanan = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        tbl_keluar_sesi_1 = new javax.swing.JButton();
        layout_footer = new javax.swing.JSplitPane();
        jPanel_footer_kiri = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point Of Sale");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1028, 1024));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setName("frame_hal_utama"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 1024));
        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jpanel_header.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_header.setPreferredSize(new java.awt.Dimension(0, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("{name}");

        javax.swing.GroupLayout jpanel_headerLayout = new javax.swing.GroupLayout(jpanel_header);
        jpanel_header.setLayout(jpanel_headerLayout);
        jpanel_headerLayout.setHorizontalGroup(
            jpanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_headerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_headerLayout.setVerticalGroup(
            jpanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout_meja_dan_menu.setMinimumSize(new java.awt.Dimension(1024, 436));
        layout_meja_dan_menu.setPreferredSize(new java.awt.Dimension(1024, 436));

        jpanel_meja2.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_meja2.setMinimumSize(new java.awt.Dimension(500, 69));
        jpanel_meja2.setPreferredSize(new java.awt.Dimension(800, 400));
        jpanel_meja2.setLayout(new java.awt.GridLayout(5, 3));

        button_generator();

        layout_meja_dan_menu.setLeftComponent(jpanel_meja2);

        jPanel2.setPreferredSize(new java.awt.Dimension(200, 472));

        jpanel_menu_kanan.setBackground(new java.awt.Color(255, 255, 255));
        jpanel_menu_kanan.setMinimumSize(new java.awt.Dimension(205, 436));
        jpanel_menu_kanan.setPreferredSize(new java.awt.Dimension(205, 436));

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Laporan penjualan");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Manajemen pesanan menu");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Manajemen Meja");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        tbl_keluar_sesi_1.setBackground(new java.awt.Color(51, 51, 51));
        tbl_keluar_sesi_1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tbl_keluar_sesi_1.setForeground(new java.awt.Color(255, 255, 255));
        tbl_keluar_sesi_1.setText("keluar");
        tbl_keluar_sesi_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbl_keluar_sesi_1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_menu_kananLayout = new javax.swing.GroupLayout(jpanel_menu_kanan);
        jpanel_menu_kanan.setLayout(jpanel_menu_kananLayout);
        jpanel_menu_kananLayout.setHorizontalGroup(
            jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_menu_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_menu_kananLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tbl_keluar_sesi_1))
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanel_menu_kananLayout.setVerticalGroup(
            jpanel_menu_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_menu_kananLayout.createSequentialGroup()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl_keluar_sesi_1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel_menu_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpanel_menu_kanan, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );

        layout_meja_dan_menu.setRightComponent(jPanel2);

        layout_footer.setMinimumSize(new java.awt.Dimension(1024, 150));
        layout_footer.setPreferredSize(new java.awt.Dimension(1024, 150));

        jPanel_footer_kiri.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_footer_kiri.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar pesanan"));
        jPanel_footer_kiri.setMinimumSize(new java.awt.Dimension(700, 100));
        jPanel_footer_kiri.setPreferredSize(new java.awt.Dimension(700, 174));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MJ001", "ORD0001", "azmi", "kasir1"}
            },
            new String [] {
                "Kode meja", "Kode order", "Pelayan", "Kasir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel_footer_kiriLayout = new javax.swing.GroupLayout(jPanel_footer_kiri);
        jPanel_footer_kiri.setLayout(jPanel_footer_kiriLayout);
        jPanel_footer_kiriLayout.setHorizontalGroup(
            jPanel_footer_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel_footer_kiriLayout.setVerticalGroup(
            jPanel_footer_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_footer_kiriLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout_footer.setLeftComponent(jPanel_footer_kiri);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        layout_footer.setRightComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(layout_footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(layout_meja_dan_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(4, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(layout_footer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(layout_meja_dan_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(150, 30));

        jMenu2.setText("Menu aplikasi");

        jMenuItem2.setText("Manajemen user aplikasi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem1.setText("Keluar aplikasi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("halaman_utama");

        setSize(new java.awt.Dimension(1024, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        tampilForm_LapPenjualan();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        tampil_formCrudMenu();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        tampil_NotAvailable();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void tbl_keluar_sesi_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbl_keluar_sesi_1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Logout ?", this.getTitle(), JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
            setClean_sesi();//clean atribut value
            tampilLogin_UserApp();
        } else if (result == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_tbl_keluar_sesi_1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        tampilCrud_UserApp();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Keluar aplikasi?", this.getTitle(), JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (result == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(HalamanLogin.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama1().setVisible(true);
                //set biar di tengah         

                //munculin framenya
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_footer_kiri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel_header;
    public static javax.swing.JPanel jpanel_meja2;
    private javax.swing.JPanel jpanel_menu_kanan;
    private javax.swing.JSplitPane layout_footer;
    private javax.swing.JSplitPane layout_meja_dan_menu;
    private javax.swing.JButton tbl_keluar_sesi_1;
    // End of variables declaration//GEN-END:variables

    
}
