/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import static pointofsale_backend.Frame_control.*;

/**
 *
 * @author Rifky <qnoy.rifky@gmail.com>
 */
public class Popup_pilihan_meja extends javax.swing.JFrame {

    /**
     * Creates new form Popup_pilihan_meja
     */
    public Popup_pilihan_meja() {
        initComponents();
        lbl_ppm_rp_total.setVisible(false);
        lbl_ppm_kdmeja.setVisible(false);        
        lbl_ppm_kode_order.setVisible(false);        
        lbl_ppm_kode_orderdetail.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ppm_Bayar = new javax.swing.JButton();
        btn_ppm_Order = new javax.swing.JButton();
        btn_ppmBack = new javax.swing.JButton();
        lbl_ppm_kode_order = new javax.swing.JLabel();
        lbl_ppm_kdmeja = new javax.swing.JLabel();
        lbl_ppm_kode_orderdetail = new javax.swing.JLabel();
        lbl_ppm_rp_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pilihan");

        btn_ppm_Bayar.setText("BAYAR");
        btn_ppm_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ppm_BayarActionPerformed(evt);
            }
        });

        btn_ppm_Order.setText("...");
        btn_ppm_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ppm_OrderActionPerformed(evt);
            }
        });

        btn_ppmBack.setText("KEMBALI");
        btn_ppmBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ppmBackActionPerformed(evt);
            }
        });

        lbl_ppm_kode_order.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ppm_kode_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ppm_kode_order.setText("?");

        lbl_ppm_kdmeja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ppm_kdmeja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ppm_kdmeja.setText("?");

        lbl_ppm_kode_orderdetail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_ppm_kode_orderdetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ppm_kode_orderdetail.setText("?");

        lbl_ppm_rp_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ppm_rp_total.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_ppm_rp_total, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ppm_kode_orderdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ppm_kdmeja, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ppm_kode_order, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ppmBack, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ppm_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ppm_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_ppm_kdmeja, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ppm_kode_order, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbl_ppm_kode_orderdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ppm_Order, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ppm_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ppmBack, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbl_ppm_rp_total)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ppm_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ppm_OrderActionPerformed
        tampil_formOrder(lbl_ppm_kdmeja.getText() ,lbl_ppm_kode_order.getText(),lbl_ppm_kode_orderdetail.getText(),lbl_ppm_rp_total.getText());
        this.setVisible(false);
    }//GEN-LAST:event_btn_ppm_OrderActionPerformed

    private void btn_ppmBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ppmBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_ppmBackActionPerformed

    private void btn_ppm_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ppm_BayarActionPerformed
        // TODO add your handling code here:
        tampilForm_bayar(lbl_ppm_kdmeja.getText() ,lbl_ppm_kode_order.getText(),lbl_ppm_kode_orderdetail.getText(),lbl_ppm_rp_total.getText());
    }//GEN-LAST:event_btn_ppm_BayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup_pilihan_meja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup_pilihan_meja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup_pilihan_meja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup_pilihan_meja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popup_pilihan_meja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ppmBack;
    public javax.swing.JButton btn_ppm_Bayar;
    public javax.swing.JButton btn_ppm_Order;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_ppm_kdmeja;
    public javax.swing.JLabel lbl_ppm_kode_order;
    public javax.swing.JLabel lbl_ppm_kode_orderdetail;
    public javax.swing.JLabel lbl_ppm_rp_total;
    // End of variables declaration//GEN-END:variables
}
